project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('AppCalendary.urls','AppCalendary'))),
    path('',include(('vacaciones.urls', 'vacaciones'))),
    path('',include(('cumpleanios.urls', 'cumpleanios'))),
]

project/cumpleanios/urls.py
from django.urls import path
from .  import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('cumpleanio/', views.cumpleanio, name='cumpleanio'),
    path('cumpleanio/list/', views.CumpleanioList.as_view(), name='cumpleanio_list'),
    path('cumpleanio/create/', views.CumpleanioCreate.as_view(), name='cumpleanio_create'),
    path('cumpleanio/detail/<int:pk>/', views.cumpleanio_detail, name='cumpleanio_detail'),
    path('cumpleanio/update/<int:pk>/', views.cumpleanio_update, name='cumpleanio_update'),
    path('cumpleanio/delete/<int:pk>/', views.cumpleanio_delete, name='cumpleanio_delete'),
]

project/cumpleanios/models.py
from django.db import models
from django.utils import timezone

# Modelos creado para obtener el mes de cumpleaños por medio de un listado.
opciones_consulta = [
    [1, "Enero"],
    [2, "Febrero"],
    [3, "Marzo"],
    [4, "Abril"],
    [5, "Mayo"],
    [6, "Junio"],
    [7, "Julio"],
    [8, "Agosto"],
    [9, "Septiembre"],
    [10, "Octubre"],
    [11, "Noviembre"],
    [12, "Diciembre"]
]

# Modelo creado para registrar los cumpleaños, dejando: nombre, apellido, dia, y mes.
class Cumpleanio(models.Model):
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    dia = models.IntegerField()
    mes = models.IntegerField(choices=opciones_consulta)

    def __str__(self):
           return f"{self.nombre} {self.apellido} {str(self.dia)} {self.get_mes_display()}"
    
    class Meta:
        verbose_name = "Cumpleaño"
        verbose_name_plural = "Cumpleaños"

project/cumpleanios/forms.py
from django import forms

from . import models

class CumpleanioForm(forms.ModelForm):
    class Meta:
        model = models.Cumpleanio
        fields = "__all__"

project/cumpleanios/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from django.urls import reverse, reverse_lazy
from .  import models
from .  import forms
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

# Create your views here.

def cumpleanio(request):
    return render(request, 'cumpleanios/cumpleanio.html')

class CumpleanioList(ListView):
    model = models.Cumpleanio
    template_name = 'cumpleanios/cumpleanio_list.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        query = self.request.GET.get('consulta', '')
        if query:
            object_list = models.Cumpleanio.objects.filter(nombre__icontains=query).order_by('mes', 'dia')
        else:
            object_list = models.Cumpleanio.objects.all().order_by('mes', 'dia')
        return object_list

class CumpleanioCreate(CreateView):
    model = models.Cumpleanio
    form_class = forms.CumpleanioForm
    success_url = reverse_lazy('cumpleanios:cumpleanio_list')

class CumpleanioDetail(DetailView):
    model = models.Cumpleanio

def cumpleanio_detail(request, pk: int):
    object = models.Cumpleanio.objects.get(id=pk)
    return render(request, 'cumpleanios/cumpleanio_detail.html', {'object': object})

def cumpleanio_update(request, pk: int):
    object = models.Cumpleanio.objects.get(id=pk)
    if request.method == 'POST':
        form = forms.CumpleanioForm(request.POST, instance=object)
        if form.is_valid():
            form.save()
            return redirect('cumpleanios:cumpleanio_list')
    else:
        form = forms.CumpleanioForm(instance=object)
    return render(request, 'cumpleanios/cumpleanio_form.html', {'form': form, 'object': object})

def cumpleanio_delete(request, pk: int):
    object = models.Cumpleanio.objects.get(id=pk)
    if request.method == 'POST':
        object.delete()
        return redirect('cumpleanios:cumpleanio_list')
    return render(request, 'cumpleanios/cumpleanio_confirm_delete.html', {'object': object})

project/cumpleanios/templates/cumpleanios/cumpleanio.html
{% extends 'AppCalendary/base.html' %}
{% load static %}

{% block title %}
    AppCalendary | Cumpleaños
{% endblock title %}

{% block content %}
<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'AppCalendary/assets/img/avataaars.svg' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Cumpleaños</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Aquí encontrás todos los cumpleaños</p>
    </div>
</header>
<br><br>
<div class="container">
    <div class="card text-center">
      <div class="card-body">
        <h5 class="card-title">Cumpleaños</h5>
        <div class="d-flex justify-content-center gap-4">
          <a href="{% url 'cumpleanios:cumpleanio_list' %} " class="btn btn-primary w-50">Listado de Cumpleaños</a>
          <a href="{% url 'cumpleanios:cumpleanio_create'%} " class="btn btn-primary w-50">Crear Cumpleaños</a>
        </div>
      </div>
    </div>
</div><br><br>
{% endblock content %}

project/cumpleanios/templates/cumpleanios/cumpleanio_confirm_delete.html
{% extends 'AppCalendary/base.html' %}
{% load static %}

{% block title %}
    AppCalendary | Eliminar Cumpleaños
{% endblock title %}

{% block content %}
<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'AppCalendary/assets/img/avataaars.svg' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Cumpleaños</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Eliminar</p>
    </div>
</header>
<div class="container my-5">
    <div class="card text-center">
        <div class="card-header">
            <h2 class="card-title">Eliminar Cumpleaños</h2>
        </div>
        <div class="card-body">
            <p class="card-text fs-5 fst-italic">¿Estás seguro de querer eliminar el cumpleaños de: <strong>{{ object.nombre }} {{ object.apellido }} -{{ object.dia }} de {{ object.get_mes_display }}</strong>?</p>
        </div>
        <div class="card-footer">
            <form method="post" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Eliminar</button>
            </form>
            <a href="{% url 'cumpleanios:cumpleanio_list' %}" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>
</div>
<br><br>
{% endblock content %}

project/cumpleanios/templates/cumpleanios/cumpleanio_create.html
{% extends 'AppCalendary/base.html' %}
{% load static %}
{% block title %}
    AppCalendary | Crear Cumpleaños
{% endblock title %}

{% block content %}
<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'AppCalendary/assets/img/avataaars.svg' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Cumpleaños</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Aquí podrás cargar tu cumpleaños</p>
    </div>
</header>

<div class="container mt-4">
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title">Cumpleaños</h5>
            
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <form method="post" class="custom-form">
                        {% csrf_token %}
                        
                        {{ form.as_p }}
                        
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Cargar cumple</button>
                            <a href="{% url 'cumpleanios:cumpleanio_list' %}" class="btn btn-secondary">Volver</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

project/cumpleanios/templates/cumpleanios/cumpleanio_detail.html
{% extends 'AppCalendary/base.html' %}
{% load static %}


{% block title %}
    AppCalendary | Detalle de Cumples
{% endblock title %}

{% block content %}
<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'AppCalendary/assets/img/avataaars.svg' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Cumples</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Detalles</p>
    </div>
</header>
<div class="container">
  <h1 class="mt-4">Detalle del Cumpleaños</h1>
    <div class="card mt-4">
        <div class="card-body">
            <h5 class="card-title">{{ object.nombre }} {{ object.apellido }}</h5>
            <p class="card-text">{{ object.dia }} de {{ object.get_mes_display }}</p>
        </div>
    </div>  
  <div class="mt-4">
    <a href="{% url 'cumpleanios:cumpleanio_list' %}" class="btn btn-primary">Volver a la Lista</a>
    <a href="{% url 'cumpleanios:cumpleanio_update' object.id %}" class="btn btn-warning">Editar</a>
    <a href="{% url 'cumpleanios:cumpleanio_delete' object.id %}" class="btn btn-danger">Eliminar</a>
  </div><br>
</div>
{% endblock content %}

project/cumpleanios/templates/cumpleanios/cumpleanio_form.html
{% extends 'AppCalendary/base.html' %}
{% load static %}

{% block title %}
    AppCalendary | {% if form.instance.pk %}Editar{% else %}Crear{% endif %} Cumple
{% endblock title %}

{% block content %}
<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar mb-5" src="{% static 'AppCalendary/assets/img/avataaars.svg' %}" alt="..." />
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Deja tú Cumple</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Escribí tu Cumple</p>
    </div>
</header>
<style>
    .custom-form {
        border: 2px solid #ced4da;
        border-radius: 10px;
        padding: 20px;
        margin-top: 20px;
    }
    .custom-form label {
        font-weight: bold;
    }
    .custom-form input,
    .custom-form select,
    .custom-form textarea {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        margin-bottom: 10px;
        box-sizing: border-box;
        text-align: center;
    }
</style>
<div class="container text-center">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="custom-form">
                <h1 class="mt-4 text-center">{% if form.instance.pk %}Editar{% else %}Crear{% endif %} Cumple</h1>
                
                <form method="post">
                    {% csrf_token %}
                    

                    <div class="mb-3">
                        <label for="id_nombre" class="form-label text-center">Nombre</label>
                        {{ form.nombre }}
                    </div>
                    
                    <div class="mb-3">
                        <label for="id_apellido" class="form-label text-center">Apellido</label>
                        {{ form.apellido }}
                    </div>
                    
                    <div class="mb-3">
                        <label for="id_dia" class="form-label text-center">Día</label>
                        {{ form.dia }}
                    </div>
                
                    <div class="mb-3">
                        <label for="id_mes" class="form-label text-center">Mes</label>
                        {{ form.mes }}
                    </div>             

                    <button type="submit" class="btn btn-primary">
                        {% if form.instance.pk %}Guardar{% else %}Crear{% endif %}
                    </button>

                    <a href="{% url 'cumpleanios:cumpleanio_list' %}" class="btn btn-secondary">Cancelar</a>

                </form>
            </div>
        </div>
    </div>
</div><br>
{% endblock content %}

project/cumpleanios/templates/cumpleanios/cumpleanio_list.html
{% extends 'AppCalendary/base.html' %}
{% load static %}

{% block title %}
    AppCalendary | Listado de Cumples
{% endblock title %}

{% block content %}
<!-- Masthead-->
<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">Cumpleaños</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light mb-0">Listado de Cumples</p>
    </div>
</header>
<div class="container">
    <h1 class="mt-4">Listado de Cumples</h1>
    <div class="mb-4">
        <form action="" method="get">
            <input type="text" class="form-control" name="consulta" placeholder="Buscar Cumpleaños">
        </form>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Nombre y Apellido</th>
                <th scope="col">Dia</th>
                <th scope="col">Mes</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.nombre }} {{ object.apellido }}</td>
                    <td>{{ object.dia }}</td>
                    <td>{{ object.get_mes_display }}</td>
                    <td>
                        <a href="{% url 'cumpleanios:cumpleanio_detail' pk=object.id %}" class="btn btn-primary me-2">Ver en Detalle</a>
                        <a href="{% url 'cumpleanios:cumpleanio_update' pk=object.id %}" class="btn btn-warning me-2">Modificar</a>
                        <a href="{% url 'cumpleanios:cumpleanio_delete' pk=object.id %}" class="btn btn-danger">Borrar</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3" class="text-center">No hay coincidencias.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'cumpleanios:cumpleanio_create' %}" class="btn btn-primary">Crear Cumpleaños</a>
    <a href="{% url 'cumpleanios:cumpleanio' %}" class="btn btn-secondary">Volver</a>
</div><br><br>
{% endblock content %}